"""
python -m myutils.gen_hicodet_baseinfo
"""

from hicodet.hicodet import HICODet


def convert_list_to_dict_str(data: list, var_name: str):
    write_text = var_name + " = {\n"
    for idx, text in enumerate(data):
        write_text += f"\t{idx}: \"{text}\",\n"
    write_text += "}\n"
    return write_text


if __name__ == "__main__":
    trainset = HICODet(
        root="hicodet/hico_20160224_det/images/train2015",
        anno_file="hicodet/instances_train2015.json"
    )

    write_text_list = [
        f"# generated by {__file__}",
        convert_list_to_dict_str(trainset.objects, "HICO_DET_OBJECT_DICT"),
        convert_list_to_dict_str(trainset.verbs, "HICO_DET_VERB_DICT"),
        convert_list_to_dict_str(trainset.interactions, "HICO_DET_HOI_DICT"),
    ]

    write_text = "\n".join(write_text_list)
    with open("myutils/hicodet_baseinfo.py", "w") as f:
        f.write(write_text)
    print("Done")
