"""
使用 pattern 获取动词的现在进行时形式，获取名词的冠词表示
pattern 的官方文档：https://github.com/clips/pattern/wiki/pattern-en

注意：pattern 仅支持 python2.7 或 python3.6

python -m myutils.gen_text
"""
import json
from pattern.en import conjugate, referenced

from myutils.hicodet_baseinfo import HICO_DET_HOI_DICT


def _get_verbing(verb):
    """获取动词的ing形式"""
    return conjugate(verb, "part")

def _get_a_or_an_noun(noun):
    """获取名词的带冠词形式"""
    return referenced(noun)


def convert_word(hoi_text_list):
    verbing_dict = {}
    article_noun_dict = {}
    for hoi_name in hoi_text_list:
        assert len(hoi_name.split(" ")) == 2
        action_text, object_text = hoi_name.split(" ")
        action_text = action_text.replace("_", " ")
        object_text = object_text.replace("_", " ")
        not_action_text = "not " + action_text

        # 获取动词和名词对应的形式
        verbing_text = _get_verbing(action_text)
        a_or_an_object_text = _get_a_or_an_noun(object_text)
        
        # 特殊情况: no_interaction
        no_interaction_flag = "interaction" in action_text and "no" in action_text
        if no_interaction_flag:
            verbing_text = "not interacting"
            not_verbing_text = "interacting"
        else:
            not_verbing_text = "not " + verbing_text

        verbing_dict[action_text] = verbing_text
        verbing_dict[not_action_text] = not_verbing_text
        article_noun_dict[object_text] = a_or_an_object_text
    return verbing_dict, article_noun_dict


def convert_dict_to_str(data: dict, var_name: str):
    write_text = var_name + " = "
    write_text += json.dumps(data, indent=4)
    write_text += "\n"
    return write_text


if __name__ == "__main__":
    hoi_text_list = list(HICO_DET_HOI_DICT.values())
    hoi_text_list += [
        # 自定义额外的 HOI 类别文本
        # ...
    ]

    verbing_dict, article_noun_dict = convert_word(hoi_text_list=hoi_text_list)

    write_text_list = [
        f"# generated by {__file__}",
        convert_dict_to_str(verbing_dict, "HICO_DET_VERBING_DICT"),
        convert_dict_to_str(article_noun_dict, "HICO_DET_OBJECT_ARTICLE_DICT")
    ]
    write_text = "\n".join(write_text_list)
    with open("myutils/dictionary.py", "a") as f:
        f.write(write_text)
    print("Done")
